spring:
  application:
    name: store
stripe:
  apiUrl: https://api.stripe.com
  timeout: 1000
  enabled: true
  currencies: USD,EUR,GBP
store:
  payProvider: stripe
email:
  host: http://localhost
  port: 8080
